/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PoolsLazyImport = createFileRoute('/pools')()
const FaucetLazyImport = createFileRoute('/faucet')()
const DebugLazyImport = createFileRoute('/debug')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PoolsLazyRoute = PoolsLazyImport.update({
  path: '/pools',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pools.lazy').then((d) => d.Route))

const FaucetLazyRoute = FaucetLazyImport.update({
  path: '/faucet',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/faucet.lazy').then((d) => d.Route))

const DebugLazyRoute = DebugLazyImport.update({
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/debug.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugLazyImport
      parentRoute: typeof rootRoute
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetLazyImport
      parentRoute: typeof rootRoute
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  DebugLazyRoute,
  FaucetLazyRoute,
  PoolsLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/debug",
        "/faucet",
        "/pools"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/debug": {
      "filePath": "debug.lazy.jsx"
    },
    "/faucet": {
      "filePath": "faucet.lazy.jsx"
    },
    "/pools": {
      "filePath": "pools.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
